# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://uoks.github.io/"
  weibo: "http://weibo.com/uoks"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "mailto:uolgks@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://cn.linkedin.com/pub/鸣-万/a2/114/803"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /avatar.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 被秒的BOSS,毕业于北京航空航天大学软件学院，有多年移动应用开发经验，现就职于IBM CDL，从事前端开发工作，业余时间仍继续移动软件开发工作。